cmake try

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -15,30 +15,31 @@ jobs:
         with:
           submodules: true
 
-      - name: Clean up EnhancedDisplaySwitch folder
-        shell: pwsh
-        run: |
-          $folderPath = "Dependencies/EnhancedDisplaySwitch"
-          
-          # Get all files in the folder, excluding the specified ones (EnhancedDisplaySwitch.cpp and EnhancedDisplaySwitch.h)
-          $filesToDelete = Get-ChildItem -Path $folderPath -Recurse | Where-Object { 
-              $_.PSIsContainer -eq $false -and $_.Name -notin @("EnhancedDisplaySwitch.cpp", "EnhancedDisplaySwitch.h")
-          }
-          
-          # Delete the files
-          foreach ($file in $filesToDelete) {
-              if ($file -ne $null) {
-                  Remove-Item -Path $file.FullName -Force
-                  Write-Host "Deleted file: $($file.FullName)"
-              }
-          }
-
-          Write-Host "Clean-up complete. Only EnhancedDisplaySwitch.cpp and EnhancedDisplaySwitch.h remain."
+      #- name: Clean up EnhancedDisplaySwitch folder
+      #  shell: pwsh
+      #  run: |
+      #    $folderPath = "Dependencies/EnhancedDisplaySwitch"
+      #    
+      #    # Get all files in the folder, excluding the specified ones (EnhancedDisplaySwitch.cpp and EnhancedDisplaySwitch.h)
+      #    $filesToDelete = Get-ChildItem -Path $folderPath -Recurse | Where-Object { 
+      #        $_.PSIsContainer -eq $false -and $_.Name -notin @("EnhancedDisplaySwitch.cpp", "EnhancedDisplaySwitch.h")
+      #    }
+      #    
+      #    # Delete the files
+      #    foreach ($file in $filesToDelete) {
+      #        if ($file -ne $null) {
+      #            Remove-Item -Path $file.FullName -Force
+      #            Write-Host "Deleted file: $($file.FullName)"
+      #        }
+      #    }
+#
+      #    Write-Host "Clean-up complete. Only EnhancedDisplaySwitch.cpp and EnhancedDisplaySwitch.h remain."
 
       - name: Set up Visual Studio shell
         uses: egor-tensin/vs-shell@v2
         with:
           arch: x64
+
 
       - name: Install Qt
         uses: jurplel/install-qt-action@v4
@@ -47,46 +48,54 @@ jobs:
           add-tools-to-path: true
           cache: true
 
-      - name: Install jom
-        id: jom-setup
-        shell: pwsh
-        run: |
-          $url = "https://download.qt.io/official_releases/jom/jom_1_1_4.zip"
-          $outputPath = "jom_1_1_4.zip"
-          Invoke-WebRequest -Uri $url -OutFile $outputPath
-          $extractPath = "jom"
-          if (-not (Test-Path $extractPath)) {
-            New-Item -ItemType Directory -Path $extractPath | Out-Null
-          }
-          Expand-Archive -Path $outputPath -DestinationPath $extractPath
-          $jomDir = "$(pwd)\jom"
-          $jomExe = "$jomDir\jom.exe"
-          if (Test-Path $jomExe) {
-            Write-Output "JOM Path: $jomDir"
-            Write-Output "::set-output name=jom_path::$jomDir"
-          } else {
-            Write-Error "jom.exe not found in $jomDir"
-            exit 1
-          }
-
-      - name: Build with qmake and jom
+      - name: Configure and build with CMake
         shell: pwsh
         run: |
           mkdir build
           cd build
-          qmake ..\QMS.pro CONFIG+=release
-          $jomPath = "${{ steps.jom-setup.outputs.jom_path }}"
-          & "$jomPath\jom.exe"
-          
-      - name: Remove source and object files
-        shell: pwsh
-        run: |
-          $buildDir = "build/release"
-          if (Test-Path $buildDir) {
-              Get-ChildItem -Path $buildDir -Include *.cpp, *.h, *.obj, *.res -Recurse | Remove-Item -Force
-          } else {
-              Write-Host "Directory not found: $buildDir"
-          }
+          cmake -DCMAKE_BUILD_TYPE=Release ..
+          cmake --build . --config Release
+
+#      - name: Install jom
+#        id: jom-setup
+#        shell: pwsh
+#        run: |
+#          $url = "https://download.qt.io/official_releases/jom/jom_1_1_4.zip"
+#          $outputPath = "jom_1_1_4.zip"
+#          Invoke-WebRequest -Uri $url -OutFile $outputPath
+#          $extractPath = "jom"
+#          if (-not (Test-Path $extractPath)) {
+#            New-Item -ItemType Directory -Path $extractPath | Out-Null
+#          }
+#          Expand-Archive -Path $outputPath -DestinationPath $extractPath
+#          $jomDir = "$(pwd)\jom"
+#          $jomExe = "$jomDir\jom.exe"
+#          if (Test-Path $jomExe) {
+#            Write-Output "JOM Path: $jomDir"
+#            Write-Output "::set-output name=jom_path::$jomDir"
+#          } else {
+#            Write-Error "jom.exe not found in $jomDir"
+#            exit 1
+#          }
+#
+#      - name: Build with qmake and jom
+#        shell: pwsh
+#        run: |
+#          mkdir build
+#          cd build
+#          qmake ..\QMS.pro CONFIG+=release
+#          $jomPath = "${{ steps.jom-setup.outputs.jom_path }}"
+#          & "$jomPath\jom.exe"
+#          
+#      - name: Remove source and object files
+#        shell: pwsh
+#        run: |
+#          $buildDir = "build/release"
+#          if (Test-Path $buildDir) {
+#              Get-ChildItem -Path $buildDir -Include *.cpp, *.h, *.obj, *.res -Recurse | Remove-Item -Force
+#          } else {
+#              Write-Host "Directory not found: $buildDir"
+#          }
 
       - name: Deploy Qt
         shell: pwsh
